config/routes.rb
Rails.application.routes.draw do

#Verb     Path(url)   controller#action(method)    Prefix
  get 'about', to: 'pages#about'
  get 'contacts', to: 'pages#contacts'

  get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'


  get 'restaurants', to: 'restaurants#index'
  post 'restaurants', to: 'restaurants#create'

  root to: 'pages#home'
  #get '/', to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    #run what ever is here
  end

  def contacts

  end

  def home

  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  RESTAURANTS = {
    1 => { name: "Dishoom", address: "Shoreditch, London", category: "indian" },
    2 => { name: "Sushi Samba", address: "City, London", category: "japanese" }
  }


  def index
    #Get a list of restaurants
    #instance method send information down stream to view (@)
    #simply a variable with @
    @category = params[:food_type]

    if params[:food_type].blank?
      @restaurants = RESTAURANTS
    else
      @restaurants = RESTAURANTS.select do |id, r|
        r[:category] == @category
      end
    end
  end

  def create
    render plain: "Add to DB restaurant '#{params[:name]}' with address '#{params[:address]}'"
  end

  def show
    #show one restaurant
    @restaurant = RESTAURANTS[params[:id].to_i]
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thespoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= yield %>

    <% time = Time.now %>
    <div>
      made with love @ Tel-Aviv <%= time %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>


<h2>Hello :)</h2>

app/views/pages/contacts.html.erb
<h1>Pages#contacts</h1>
<p>Find me in app/views/pages/contacts.html.erb</p>

app/views/pages/home.html.erb
<h1>The SPOON </h1>

<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="submit">
</form>

app/views/restaurants/index.html.erb
<h1>List of Amazing Tel-Aviv Places</h1>

<form method="get" action="/restaurants" >

  <input type="text" name="food_type" placeholder="What kind of food?">
  <input type="submit">
</form>

<ul>
  <% @restaurants.each do |id, restaurant| %>
    <li>
      <%= restaurant[:name]%> - <%= restaurant[:category]%> -
      <%= link_to 'details', restaurant_path(id) %>
      <% #link_to string, prefix_path() %>
    </li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<h1><%= @restaurant[:name] %></h1>
<p><%= @restaurant[:address] %></p>

<p>Great place</p>